import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

# --- Config ---
INPUT_FILE = "top_drone_remote_sensing_links.txt"
EMAIL_SENDER = os.getenv("EMAIL_USER")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
EMAIL_RECEIVER = "filmfer@gmail.com"
WEB_FILE = "index.html"  # The file that will become your website

def parse_news_file():
    """Reads the text file and parses the top 5 most recent entries."""
    if not os.path.exists(INPUT_FILE):
        return []

    articles = []
    current_article = {}
    
    try:
        with open(INPUT_FILE, "r", encoding="utf-8") as f:
            lines = f.readlines()
            
        for line in reversed(lines):
            line = line.strip()
            if "Link: " in line:
                current_article['link'] = line.split("Link: ")[1]
            elif "Snippet: " in line:
                current_article['summary'] = line.split("Snippet: ")[1]
            elif "Title: " in line:
                current_article['title'] = line.split("Title: ")[1]
            elif "----------------------------------------" in line:
                if 'title' in current_article:
                    articles.append(current_article)
                current_article = {}
        return articles[:5]
    except Exception as e:
        print(f"❌ Error parsing file: {e}")
        return []

def determine_icon(title, summary):
    """Selects an emoji based on keywords."""
    text = (str(title) + " " + str(summary)).lower()
    if any(k in text for k in ['satellite', 'orbit', 'space', 'sar']):
        return "🛰️"
    elif any(k in text for k in ['drone', 'uav', 'quadcopter', 'vtol']):
        return "🚁"
    return "📡"

def generate_html(articles, is_web_version=False):
    """Generates a modern HTML newsletter or webpage."""
    
    # Header difference: Web version has a "Live" badge
    header_extra = '<span style="background:#e74c3c; padding:4px 8px; border-radius:4px; font-size:12px; vertical-align:middle;">LIVE WEB EDITION</span>' if is_web_version else ''
    
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>UAV & Remote Sensing Weekly</title>
        <style>
            body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; background-color: #f4f4f9; margin: 0; padding: 0; color: #333; }}
            .container {{ max-width: 600px; margin: 40px auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 10px 25px rgba(0,0,0,0.1); }}
            .header {{ background: linear-gradient(135deg, #1a2980 0%, #26d0ce 100%); color: #ffffff; padding: 40px 20px; text-align: center; }}
            .header h1 {{ margin: 0; font-size: 28px; font-weight: 700; letter-spacing: -0.5px; }}
            .header p {{ margin: 10px 0 0; font-size: 16px; opacity: 0.9; }}
            .content {{ padding: 30px; background-color: #ffffff; }}
            .card {{ background: #f8f9fa; border-left: 5px solid #26d0ce; margin-bottom: 25px; padding: 20px; border-radius: 8px; transition: transform 0.2s; }}
            .card:hover {{ transform: translateY(-2px); box-shadow: 0 4px 12px rgba(0,0,0,0.05); }}
            .card h2 {{ margin: 0 0 10px; font-size: 20px; color: #2c3e50; }}
            .card p {{ margin: 0 0 15px; color: #666; line-height: 1.6; font-size: 15px; }}
            .btn {{ display: inline-block; background-color: #1a2980; color: #fff; text-decoration: none; padding: 10px 20px; border-radius: 50px; font-size: 13px; font-weight: bold; }}
            .footer {{ background-color: #2c3e50; color: #bdc3c7; text-align: center; padding: 30px; font-size: 13px; }}
            .footer a {{ color: #26d0ce; text-decoration: none; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>UAV NewTech Weekly {header_extra}</h1>
                <p>Top 5 Insights for {datetime.now().strftime('%B %d, %Y')}</p>
            </div>
            <div class="content">
    """

    for article in articles:
        icon = determine_icon(article.get('title', ''), article.get('summary', ''))
        html += f"""
                <div class="card">
                    <h2>{icon} {article.get('title', 'No Title')}</h2>
                    <p>{article.get('summary', 'No summary.')}</p>
                    <a href="{article.get('link', '#')}" target="_blank" class="btn">READ SOURCE →</a>
                </div>
        """

    footer_text = "Generated by GitHub Actions Agent"
    if is_web_version:
        footer_text = f"Updated automatically every Monday.<br> <a href='https://github.com/filmfer/UAVNewTech'>View Source Code on GitHub</a>"

    html += f"""
            </div>
            <div class="footer">
                <p>{footer_text}</p>
            </div>
        </div>
    </body>
    </html>
    """
    return html

def main():
    print("📰 Parsing news...")
    top_news = parse_news_file()
    
    if not top_news:
        print("ℹ️ No news found.")
        return

    # 1. Generate and Send Email
    if EMAIL_SENDER and EMAIL_PASSWORD:
        print("📧 Sending Email...")
        email_html = generate_html(top_news, is_web_version=False)
        # (Insert your send_email logic here - kept short for brevity)
        msg = MIMEMultipart()
        msg['From'] = f"UAV News Agent <{EMAIL_SENDER}>"
        msg['To'] = EMAIL_RECEIVER
        msg['Subject'] = f"🚀 UAV Weekly: {datetime.now().strftime('%Y-%m-%d')}"
        msg.attach(MIMEText(email_html, 'html'))
        try:
            with smtplib.SMTP_SSL('smtp.gmail.com', 465) as s:
                s.login(EMAIL_SENDER, EMAIL_PASSWORD)
                s.send_message(msg)
            print("✅ Email Sent.")
        except Exception as e:
            print(f"❌ Email Failed: {e}")

    # 2. Generate and Save Web Version
    print(f"💾 Saving {WEB_FILE}...")
    web_html = generate_html(top_news, is_web_version=True)
    with open(WEB_FILE, "w", encoding="utf-8") as f:
        f.write(web_html)
    print("✅ Web file saved.")

if __name__ == "__main__":
    main()
